# Serene Nebula Theme Configuration

[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
width = 500
min_width = 500

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true

[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 28
theme = ""

[ui.window.box.margins]
top = 180

[ui.window.box.ai_scroll]
name = "aiScroll"
h_align = "fill"
v_align = "fill"
max_height = 350
min_width = 450
height = 350
width = 450

[ui.window.box.ai_scroll.margins]
top = 12

[ui.window.box.ai_scroll.list]
name = "aiList"
orientation = "vertical"
width = 450
spacing = 12

[ui.window.box.ai_scroll.list.item]
name = "aiItem"
h_align = "fill"
v_align = "fill"
x_align = 0
y_align = 0
wrap = true

[ui.window.box.scroll.list]
marker_color = "#8A2BE2"
max_height = 350
max_width = 450
min_width = 450
width = 450

[ui.window.box.scroll.list.item.activation_label]
h_align = "fill"
v_align = "fill"
width = 22
x_align = 0.5
y_align = 0.5

[ui.window.box.scroll.list.item.icon]
pixel_size = 28
theme = ""

[ui.window.box.scroll.list.margins]
top = 12

[ui.window.box.search.prompt]
name = "prompt"
icon = "edit-find"
theme = ""
pixel_size = 20
h_align = "center"
v_align = "center"

[ui.window.box.search.clear]
name = "clear"
icon = "edit-clear"
theme = ""
pixel_size = 20
h_align = "center"
v_align = "center"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = true

[ui.window.box.search.spinner]
hide = true
