# Aurora Borealis Theme Configuration

[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
width = 580 # Wider box to show more content
min_width = 580

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true

[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 32
theme = ""

[ui.window.box.margins]
top = 100 # Significantly less top margin to show background
bottom = 100 # Also add bottom margin
left = 50 # Add side margins
right = 50

[ui.window.box.ai_scroll]
name = "aiScroll"
h_align = "fill"
v_align = "fill"
max_height = 400
min_width = 520
height = 400
width = 520

[ui.window.box.ai_scroll.margins]
top = 20

[ui.window.box.ai_scroll.list]
name = "aiList"
orientation = "vertical"
width = 520
spacing = 15

[ui.window.box.ai_scroll.list.item]
name = "aiItem"
h_align = "fill"
v_align = "fill"
x_align = 0
y_align = 0
wrap = true

[ui.window.box.scroll.list]
marker_color = "#32CD32" # LimeGreen
max_height = 400
max_width = 520
min_width = 520
width = 520

[ui.window.box.scroll.list.item.activation_label]
h_align = "fill"
v_align = "fill"
width = 28
x_align = 0.5
y_align = 0.5

[ui.window.box.scroll.list.item.icon]
pixel_size = 32
theme = ""

[ui.window.box.scroll.list.margins]
top = 20

[ui.window.box.search.prompt]
name = "prompt"
icon = "edit-find"
theme = ""
pixel_size = 24
h_align = "center"
v_align = "center"

[ui.window.box.search.clear]
name = "clear"
icon = "edit-clear"
theme = ""
pixel_size = 24
h_align = "center"
v_align = "center"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = true

[ui.window.box.search.spinner]
hide = true
