# SPDX-FileCopyrightText: yar2000T <https://github.com/yar2000T>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["*.jpg", "*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "yar2000T <https://github.com/yar2000T>"
SPDX-License-Identifier = "CC-BY-4.0"

# Font downloaded from: https://www.nerdfonts.com/font-downloads
[[annotations]]
path = ["0xProtoNerdFontPropo-Regular.otf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) 2023, 0xType Project Authors (https://github.com/0xType)"
SPDX-License-Identifier = "OFL-1.1"
